query topAnime(
  $page: Int
  $perPage: Int
  $sort: [MediaSort]
  $type: MediaType
) {
  Page(page: $page, perPage: $perPage) {
    media(sort: $sort, type: $type) {
      title {
        userPreferred
      }
      episodes
      genres
      idMal
      coverImage {
        medium
      }
      status
      description
    }
  }
}
